//visitor.trackingServer = "accstandardbank.d1.sc.omtrdc.net"; // same as s.trackingServer
//visitor.trackingServerSecure = "accstandardbank.d1.sc.omtrdc.net"; //same as s.trackingServerSecure
/*
/*
 ============== DO NOT ALTER ANYTHING BELOW THIS LINE ! ============

 Adobe Visitor API for JavaScript version: 1.4
 Copyright 1996-2013 Adobe, Inc. All Rights Reserved
 More info available at http://www.omniture.com
*/
function Visitor(m,w){if(!m)throw"Visitor requires Adobe Marketing Cloud Org ID";var a=this;a.version="1.4";var k=window,p=k.Visitor;k.s_c_in||(k.s_c_il=[],k.s_c_in=0);a._c="Visitor";a._il=k.s_c_il;a._in=k.s_c_in;a._il[a._in]=a;k.s_c_in++;var n=k.document,h=k.Ha;h||(h=null);var i=k.Ia;i||(i=!0);var j=k.Ga;j||(j=!1);a.Q=function(a){var b=0,c,e;if(a)for(c=0;c<a.length;c++)e=a.charCodeAt(c),b=(b<<5)-b+e,b&=b;return b};a.p=function(a){var b="0123456789",c="",e="",f,g=8,i=10,h=10;if(1==a){b+="ABCDEF";
for(a=0;16>a;a++)f=Math.floor(Math.random()*g),c+=b.substring(f,f+1),f=Math.floor(Math.random()*g),e+=b.substring(f,f+1),g=16;return c+"-"+e}for(a=0;19>a;a++)f=Math.floor(Math.random()*i),c+=b.substring(f,f+1),0==a&&9==f?i=3:(1==a||2==a)&&10!=i&&2>f?i=10:2<a&&(i=10),f=Math.floor(Math.random()*h),e+=b.substring(f,f+1),0==a&&9==f?h=3:(1==a||2==a)&&10!=h&&2>f?h=10:2<a&&(h=10);return c+e};a.ka=function(){var a;!a&&k.location&&(a=k.location.hostname);if(a)if(/^[0-9.]+$/.test(a))a="";else{var b=a.split("."),
c=b.length-1,e=c-1;1<c&&2>=b[c].length&&(2==b[c-1].length||0>",ac,ad,ae,af,ag,ai,al,am,an,ao,aq,ar,as,at,au,aw,ax,az,ba,bb,be,bf,bg,bh,bi,bj,bm,bo,br,bs,bt,bv,bw,by,bz,ca,cc,cd,cf,cg,ch,ci,cl,cm,cn,co,cr,cu,cv,cw,cx,cz,de,dj,dk,dm,do,dz,ec,ee,eg,es,et,eu,fi,fm,fo,fr,ga,gb,gd,ge,gf,gg,gh,gi,gl,gm,gn,gp,gq,gr,gs,gt,gw,gy,hk,hm,hn,hr,ht,hu,id,ie,im,in,io,iq,ir,is,it,je,jo,jp,kg,ki,km,kn,kp,kr,ky,kz,la,lb,lc,li,lk,lr,ls,lt,lu,lv,ly,ma,mc,md,me,mg,mh,mk,ml,mn,mo,mp,mq,mr,ms,mt,mu,mv,mw,mx,my,na,nc,ne,nf,ng,nl,no,nr,nu,nz,om,pa,pe,pf,ph,pk,pl,pm,pn,pr,ps,pt,pw,py,qa,re,ro,rs,ru,rw,sa,sb,sc,sd,se,sg,sh,si,sj,sk,sl,sm,sn,so,sr,st,su,sv,sx,sy,sz,tc,td,tf,tg,th,tj,tk,tl,tm,tn,to,tp,tr,tt,tv,tw,tz,ua,ug,uk,us,uy,uz,va,vc,ve,vg,vi,vn,vu,wf,ws,yt,".indexOf(","+
b[c]+","))&&e--;if(0<e)for(a="";c>=e;)a=b[c]+(a?".":"")+a,c--}return a};a.cookieRead=function(a){var a=encodeURIComponent(a),b=(";"+n.cookie).split(" ").join(";"),c=b.indexOf(";"+a+"="),e=0>c?c:b.indexOf(";",c+1);return 0>c?"":decodeURIComponent(b.substring(c+2+a.length,0>e?b.length:e))};a.cookieWrite=function(d,b,c){var e=a.cookieLifetime,f,b=""+b,e=e?(""+e).toUpperCase():"";c&&"SESSION"!=e&&"NONE"!=e?(f=""!=b?parseInt(e?e:0):-60)?(c=new Date,c.setTime(c.getTime()+1E3*f)):1==c&&(c=new Date,f=c.getYear(),
c.setYear(f+2+(1900>f?1900:0))):c=0;return d&&"NONE"!=e?(n.cookie=encodeURIComponent(d)+"="+encodeURIComponent(b)+"; path=/;"+(c?" expires="+c.toGMTString()+";":"")+(a.cookieDomain?" domain="+a.cookieDomain+";":""),a.cookieRead(d)==b):0};a.g=h;a.M=function(a,b){try{"function"==typeof a?a.apply(k,b):a[1].apply(a[0],b)}catch(c){}};a.na=function(d,b){b&&(a.g==h&&(a.g={}),void 0==a.g[d]&&(a.g[d]=[]),a.g[d].push(b))};a.o=function(d,b){if(a.g!=h){var c=a.g[d];if(c)for(;0<c.length;)a.M(c.shift(),b)}};a.k=
h;a.la=function(d,b,c){var e=0,f=0,g;if(b&&n){for(g=0;!e&&2>g;){try{e=(e=n.getElementsByTagName(0<g?"HEAD":"head"))&&0<e.length?e[0]:0}catch(i){e=0}g++}if(!e)try{n.body&&(e=n.body)}catch(j){e=0}if(e)for(g=0;!f&&2>g;){try{f=n.createElement(0<g?"SCRIPT":"script")}catch(k){f=0}g++}}!b||!e||!f?c&&c():(f.type="text/javascript",f.setAttribute("async","async"),f.src=b,e.firstChild?e.insertBefore(f,e.firstChild):e.appendChild(f),c&&(a.k==h&&(a.k={}),a.k[d]=setTimeout(c,a.loadTimeout)))};a.ja=function(d){a.k!=
h&&a.k[d]&&(clearTimeout(a.k[d]),a.k[d]=0)};a.R=j;a.S=j;a.isAllowed=function(){if(!a.R&&(a.R=i,a.cookieRead(a.cookieName)||a.cookieWrite(a.cookieName,"T",1)))a.S=i;return a.S};a.a=h;a.e=h;var z=a.Ta;z||(z="MC");var q=a.Ya;q||(q="MCMID");var A=a.Va;A||(A="MCCIDH");var C=a.Ua;C||(C="MCAS");var B=a.Xa;B||(B="MCSYNCS");var D=a.Wa;D||(D="MCIDTS");var x=a.Ra;x||(x="A");var l=a.Oa;l||(l="MCAID");var v=a.Sa;v||(v="AAM");var u=a.Qa;u||(u="MCAAMLH");var o=a.Pa;o||(o="MCAAMB");var r=a.Za;r||(r="NONE");a.A=0;
a.P=function(){if(!a.A){var d=a.version;a.audienceManagerServer&&(d+="|"+a.audienceManagerServer);a.audienceManagerServerSecure&&(d+="|"+a.audienceManagerServerSecure);if(a.audienceManagerCustomerIDDPIDs)for(var b in a.audienceManagerCustomerIDDPIDs)!Object.prototype[b]&&a.audienceManagerCustomerIDDPIDs[b]&&(d+=b+"="+a.audienceManagerCustomerIDDPIDs[b]);a.A=a.Q(d)}return a.A};a.T=j;a.f=function(){if(!a.T){a.T=i;var d=a.P(),b=j,c=a.cookieRead(a.cookieName),e,f,g,F=new Date;a.a==h&&(a.a={});if(c&&"T"!=
c){c=c.split("|");c[0].match(/^[\-0-9]+$/)&&(parseInt(c[0])!=d&&(b=i),c.shift());1==c.length%2&&c.pop();for(d=0;d<c.length;d+=2)e=c[d].split("-"),f=e[0],g=c[d+1],e=1<e.length?parseInt(e[1]):0,b&&(f==A&&(g=""),0<e&&(e=F.getTime()/1E3-60)),f&&g&&(a.c(f,g,1),0<e&&(a.a["expire"+f]=e,F.getTime()>=1E3*e&&(a.e||(a.e={}),a.e[f]=i)))}if(!a.b(l)&&(c=a.cookieRead("s_vi")))c=c.split("|"),1<c.length&&0<=c[0].indexOf("v1")&&(g=c[1],d=g.indexOf("["),0<=d&&(g=g.substring(0,d)),g&&g.match(/^[0-9a-fA-F\-]+$/)&&a.c(l,
g))}};a.oa=function(){var d=a.P(),b,c;for(b in a.a)!Object.prototype[b]&&a.a[b]&&"expire"!=b.substring(0,6)&&(c=a.a[b],d+=(d?"|":"")+b+(a.a["expire"+b]?"-"+a.a["expire"+b]:"")+"|"+c);a.cookieWrite(a.cookieName,d,1)};a.b=function(d,b){return a.a!=h&&(b||!a.e||!a.e[d])?a.a[d]:h};a.c=function(d,b,c){a.a==h&&(a.a={});a.a[d]=b;c||a.oa()};a.m=function(d,b){var c=new Date;c.setTime(c.getTime()+1E3*b);a.a==h&&(a.a={});a.a["expire"+d]=Math.floor(c.getTime()/1E3);0>b?(a.e||(a.e={}),a.e[d]=i):a.e&&(a.e[d]=j)};
a.O=function(a){if(a&&("object"==typeof a&&(a=a.d_mid?a.d_mid:a.visitorID?a.visitorID:a.id?a.id:a.uuid?a.uuid:""+a),a&&(a=a.toUpperCase(),"NOTARGET"==a&&(a=r)),!a||a!=r&&!a.match(/^[0-9a-fA-F\-]+$/)))a="";return a};a.j=function(d,b){a.ja(d);a.i!=h&&(a.i[d]=j);if(d==z){var c=a.b(q);if(!c){c="object"==typeof b&&b.mid?b.mid:a.O(b);if(!c){if(a.t){a.getAnalyticsVisitorID(h,j,i);return}c=a.p()}a.c(q,c)}if(!c||c==r)c="";"object"==typeof b&&((b.d_region||b.dcs_region||b.d_blob||b.blob)&&a.j(v,b),a.t&&b.mid&&
a.j(x,{id:b.id}));a.o(q,[c])}if(d==v&&"object"==typeof b){c=604800;void 0!=b.id_sync_ttl&&b.id_sync_ttl&&(c=parseInt(b.id_sync_ttl));var e=a.b(u);e||((e=b.d_region)||(e=b.dcs_region),e&&(a.m(u,c),a.c(u,e)));e||(e="");a.o(u,[e]);e=a.b(o);if(b.d_blob||b.blob)(e=b.d_blob)||(e=b.blob),a.m(o,c),a.c(o,e);e||(e="");a.o(o,[e]);!b.error_msg&&a.r&&a.c(A,a.r);a.idSyncDisableSyncs?s.$=i:(s.$=j,s.Ea({xa:b.ibs,d:b.subdomain}))}if(d==x){c=a.b(l);c||((c=a.O(b))?a.m(o,-1):c=r,a.c(l,c));if(!c||c==r)c="";a.o(l,[c])}};
a.i=h;a.q=function(d,b,c,e){var f="",g;if(a.isAllowed()&&(a.f(),f=a.b(d),!f&&(d==q?g=z:d==u||d==o?g=v:d==l&&(g=x),g))){if(b&&(a.i==h||!a.i[g]))a.i==h&&(a.i={}),a.i[g]=i,a.la(g,b,function(){if(!a.b(d)){var b="";d==q?b=a.p():g==v&&(b={error_msg:"timeout"});a.j(g,b)}});a.na(d,c);b||a.j(g,{id:r});return""}if((d==q||d==l)&&f==r)f="",e=i;c&&e&&a.M(c,[f]);return f};a._setMarketingCloudFields=function(d){a.f();a.j(z,d)};a.setMarketingCloudVisitorID=function(d){a._setMarketingCloudFields(d)};a.t=j;a.getMarketingCloudVisitorID=
function(d,b){return a.isAllowed()?(a.marketingCloudServer&&0>a.marketingCloudServer.indexOf(".demdex.net")&&(a.t=i),a.q(q,a.z("_setMarketingCloudFields"),d,b)):""};a.ma=function(){a.getAudienceManagerBlob()};a.h={};a.N=j;a.r="";a.setCustomerIDs=function(d){a.h=d;if(a.isAllowed()){a.f();var d=a.b(A),b="",c,e;d||(d=0);for(c in a.h)e=a.h[c],!Object.prototype[c]&&e&&(b+=(b?"|":"")+c+"|"+e);a.r=a.Q(b);a.r!=d&&(a.N=i,a.ma())}};a.getCustomerIDs=function(){return a.h};a._setAnalyticsFields=function(d){a.f();
a.j(x,d)};a.setAnalyticsVisitorID=function(d){a._setAnalyticsFields(d)};a.getAnalyticsVisitorID=function(d,b,c){if(a.isAllowed()){var e="";c||(e=a.getMarketingCloudVisitorID(function(){a.getAnalyticsVisitorID(d,i)}));if(e||c){var f=c?a.marketingCloudServer:a.trackingServer,g="";a.loadSSL&&(c?a.marketingCloudServerSecure&&(f=a.marketingCloudServerSecure):a.trackingServerSecure&&(f=a.trackingServerSecure));f&&(g="http"+(a.loadSSL?"s":"")+"://"+f+"/id?callback=s_c_il%5B"+a._in+"%5D._set"+(c?"MarketingCloud":
"Analytics")+"Fields&mcorgid="+encodeURIComponent(a.marketingCloudOrgID)+(e?"&mid="+e:""));return a.q(c?q:l,g,d,b)}}return""};a._setAudienceManagerFields=function(d){a.f();a.j(v,d)};a.z=function(d){var b=a.audienceManagerServer,c="",e=a.b(q),f=a.b(o,i),g=a.b(l),g=g&&g!=r?"&d_cid_ic=AVID%01"+encodeURIComponent(g):"",h="",j,k;a.loadSSL&&a.audienceManagerServerSecure&&(b=a.audienceManagerServerSecure);if(b){if(a.h)for(j in a.h)if(!Object.prototype[j]&&(c=a.h[j]))g+="&d_cid_ic="+encodeURIComponent(j)+
"%01"+encodeURIComponent(c),a.audienceManagerCustomerIDDPIDs&&(k=a.audienceManagerCustomerIDDPIDs[j])&&(h+="&d_cid="+k+"%01"+encodeURIComponent(c));d||(d="_setAudienceManagerFields");c="http"+(a.loadSSL?"s":"")+"://"+b+"/id?d_rtbd=json&d_ver=2"+(!e&&a.t?"&d_verify=1":"")+"&d_orgid="+encodeURIComponent(a.marketingCloudOrgID)+"&d_nsid="+(a.idSyncContainerID||0)+(e?"&d_mid="+e:"")+(f?"&d_blob="+encodeURIComponent(f):"")+g+h+"&d_cb=s_c_il%5B"+a._in+"%5D."+d}return c};a.getAudienceManagerLocationHint=
function(d,b){if(a.isAllowed()&&a.getMarketingCloudVisitorID(function(){a.getAudienceManagerLocationHint(d,i)})){var c=a.b(l);c||(c=a.getAnalyticsVisitorID(function(){a.getAudienceManagerLocationHint(d,i)}));if(c)return a.q(u,a.z(),d,b)}return""};a.getAudienceManagerBlob=function(d,b){if(a.isAllowed()&&a.getMarketingCloudVisitorID(function(){a.getAudienceManagerBlob(d,i)})){var c=a.b(l);c||(c=a.getAnalyticsVisitorID(function(){a.getAudienceManagerBlob(d,i)}));if(c)return c=a.z(),a.N&&a.m(o,-1),a.q(o,
c,d,b)}return""};p.AUTH_STATE_UNAUTHENTICATED=0;p.AUTH_STATE_AUTHENTICATED=1;p.AUTH_STATE_ASSUMED_AUTHENTICATED=2;p.AUTH_STATE_LOGGEDOUT=3;a.setAuthState=function(d){a.isAllowed()&&(a.f(),a.c(C,d))};a.getAuthState=function(){return a.isAllowed()?(a.f(),a.b(C)):0};a.n="";a.s={};a.B="";a.C={};a.getSupplementalDataID=function(d,b){!a.n&&!b&&(a.n=a.p(1));var c=a.n;a.B&&!a.C[d]?(c=a.B,a.C[d]=i):c&&(a.s[d]&&(a.B=a.n,a.C=a.s,a.n=c=!b?a.p(1):"",a.s={}),c&&(a.s[d]=i));return c};var t={l:!!k.postMessage,ha:1,
L:864E5};a.Ja=t;a.V={postMessage:function(a,b,c){var e=1;b&&(t.l?c.postMessage(a,b.replace(/([^:]+:\/\/[^\/]+).*/,"$1")):b&&(c.location=b.replace(/#.*$/,"")+"#"+ +new Date+e++ +"&"+a))},H:function(a,b){var c;try{if(t.l)if(a&&(c=function(c){if("string"===typeof b&&c.origin!==b||"[object Function]"===Object.prototype.toString.call(b)&&!1===b(c.origin))return!1;a(c)}),window.addEventListener)window[a?"addEventListener":"removeEventListener"]("message",c,!1);else window[a?"attachEvent":"detachEvent"]("onmessage",
c)}catch(e){}}};var E={W:function(){if(n.addEventListener)return function(a,b,c){a.addEventListener(b,function(a){"function"===typeof c&&c(a)},j)};if(n.attachEvent)return function(a,b,c){a.attachEvent("on"+b,function(a){"function"===typeof c&&c(a)})}}(),map:function(a,b){if(Array.prototype.map)return a.map(b);if(void 0===a||a===h)throw new TypeError;var c=Object(a),e=c.length>>>0;if("function"!==typeof b)throw new TypeError;for(var f=Array(e),g=0;g<e;g++)g in c&&(f[g]=b.call(b,c[g],g,c));return f},
ua:function(a,b){return this.map(a,function(a){return encodeURIComponent(a)}).join(b)}};a.Na=E;var s={ia:3E4,K:649,ga:j,ea:j,id:h,F:h,Z:function(a){if("string"===typeof a)return a=a.split("/"),a[0]+"//"+a[2]},d:h,url:h,wa:function(){var d="http://fast.",b="?d_nsid="+a.idSyncContainerID+"#"+encodeURIComponent(n.location.href);this.d||(this.d="nosubdomainreturned");a.loadSSL&&(d=a.idSyncSSLUseAkamai?"https://fast.":"https://");d=d+this.d+".demdex.net/dest5.html"+b;this.F=this.Z(d);this.id="destination_publishing_iframe_"+
this.d+"_"+a.idSyncContainerID;return d},qa:function(){var d="?d_nsid="+a.idSyncContainerID+"#"+encodeURIComponent(n.location.href);"string"===typeof a.w&&a.w.length&&(this.id="destination_publishing_iframe_"+(new Date).getTime()+"_"+a.idSyncContainerID,this.F=this.Z(a.w),this.url=a.w+d)},$:h,J:j,aa:j,I:j,u:[],Ba:[],Ca:[],ba:t.l?15:100,G:[],za:[],Y:i,ca:j,X:function(){this.J=i;var a=this,b=document.createElement("iframe");b.id=this.id;b.style.cssText="display: none; width: 0; height: 0;";b.src=this.url;
E.W(b,"load",function(){b.className="loaded";a.aa=i;a.v()});n.body.appendChild(b);this.ya=b},v:function(d){var b=this;d===Object(d)&&this.G.push(d);if((this.ca||!t.l)&&this.G.length)this.Da(this.G.shift()),this.v();!a.idSyncDisableSyncs&&this.aa&&this.u.length&&!this.I&&(this.ea||(this.ea=i,setTimeout(function(){b.ba=t.l?15:150},this.ia)),this.I=i,this.da())},Da:function(a){var b=encodeURIComponent,c,e,f,g,i;if((c=a.xa)&&c instanceof Array&&(e=c.length))for(f=0;f<e;f++)g=c[f],i=[b("ibs"),b(g.id||
""),b(g.tag||""),E.ua(g.url||[],","),b(g.fa||""),"","",g.va?"true":"false"],this.Y?this.D(i.join("|")):g.va&&this.ra(g,i.join("|"));this.za.push(a)},ra:function(d,b){a.f();var c=a.b(B),e=j,f=j,g=Math.ceil((new Date).getTime()/t.L);if(c){if(c=c.split("*"),f=this.Fa(c,d.id,g),e=f.sa,f=f.ta,!e||!f)this.D(b),c.push(d.id+"-"+(g+Math.ceil(d.fa/60/24))),this.Aa(c),a.c(B,c.join("*"))}else this.D(b),a.c(B,d.id+"-"+(g+Math.ceil(d.fa/60/24)))},Fa:function(a,b,c){var e=j,f=j,g,h,k;for(h=0;h<a.length;h++)g=a[h],
k=parseInt(g.split("-")[1],10),g.match("^"+b+"-")?(e=i,c<k?f=i:(a.splice(h,1),h--)):c>=k&&(a.splice(h,1),h--);return{sa:e,ta:f}},Aa:function(a){if(a.join("*").length>this.K)for(a.sort(function(a,c){return parseInt(a.split("-")[1],10)-parseInt(c.split("-")[1],10)});a.join("*").length>this.K;)a.shift()},D:function(d){var b=encodeURIComponent;this.u.push((a.La?b("---destpub-debug---"):b("---destpub---"))+d)},da:function(){var d=this,b;this.u.length?(b=this.u.shift(),a.V.postMessage(b,this.url,this.ya.contentWindow),
this.Ba.push(b),setTimeout(function(){d.da()},this.ba)):this.I=j},H:function(a){var b=/^---destpub-to-parent---/;"string"===typeof a&&b.test(a)&&(b=a.replace(b,"").split("|"),"canSetThirdPartyCookies"===b[0]&&(this.Y="true"===b[1]?i:j,this.ca=i,this.v()),this.Ca.push(a))},Ea:function(d){this.url===h&&(this.d="string"===typeof a.U&&a.U.length?a.U:d.d||"",this.url=this.wa());this.d&&"nosubdomainreturned"!==this.d&&this.ga&&!this.J&&this.X();"function"===typeof a.idSyncIDCallResult?a.idSyncIDCallResult(d):
this.v(d);"function"===typeof a.idSyncAfterIDCallResult&&a.idSyncAfterIDCallResult(d)},pa:function(d,b){return a.Ma||!d||b-d>t.ha}};a.Ka=s;0>m.indexOf("@")&&(m+="@AdobeOrg");a.marketingCloudOrgID=m;a.cookieName="AMCV_"+m;a.cookieDomain=a.ka();a.cookieDomain==k.location.hostname&&(a.cookieDomain="");a.loadSSL=0<=k.location.protocol.toLowerCase().indexOf("https");a.loadTimeout=500;a.marketingCloudServer=a.audienceManagerServer="dpm.demdex.net";if(w&&"object"==typeof w){for(var y in w)Object.prototype[y]||
(a[y]=w[y]);a.idSyncContainerID=a.idSyncContainerID||0;a.f();p=a.b(D);y=Math.ceil((new Date).getTime()/t.L);!a.idSyncDisableSyncs&&s.pa(p,y)&&(a.m(o,-1),a.c(D,y));a.getMarketingCloudVisitorID();a.getAudienceManagerLocationHint();a.getAudienceManagerBlob()}if(!a.idSyncDisableSyncs){s.qa();E.W(window,"load",function(){var a=s;a.ga=i;a.d&&"nosubdomainreturned"!==a.d&&a.url&&!a.J&&a.X()});try{a.V.H(function(a){s.H(a.data)},s.F)}catch(G){}}}
Visitor.getInstance=function(m,w){var a,k=window.s_c_il,p;0>m.indexOf("@")&&(m+="@AdobeOrg");if(k)for(p=0;p<k.length;p++)if((a=k[p])&&"Visitor"==a._c&&a.marketingCloudOrgID==m)return a;return new Visitor(m,w)};
